In [3]:
import add

print(add.add(3,4))

7


In [4]:
import math


In [5]:
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'cbrt', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'exp2', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'lcm', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'nextafter', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'sumprod', 'tan', 'tanh', 'tau', 'trunc', 'ulp']


In [6]:
print(math.factorial(5))

120


In [7]:
print(math.ceil(20.7))

21


In [8]:
#print(math.floor(20.7))
import random

random.randint

random.choice([1,2,3,4,5]
              )

2

In [9]:
print(math.ceil(math.cos(90)))

0


In [10]:
pip install pandas


  Using cached pandas-2.2.1-cp312-cp312-win_amd64.whl.metadata (19 kB)
Using cached pandas-2.2.1-cp312-cp312-win_amd64.whl (11.5 MB)
Note: you may need to restart the kernel to use updated packages.


In [11]:
import numpy as np

In [12]:
arr = np.array([2,1,3,4,6,32])

np.sort(arr)


array([ 1,  2,  3,  4,  6, 32])

In [15]:
b = np.array([1,2,3,4])
a = np.array([5,6,7,8])

np.sort(np.concatenate((a,b)))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6]])

np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
a = np.array([[3,4,5],[3,2,2]])

a.ndim

2

In [23]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [24]:
b = a.reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [26]:
data = np.array([1,2,3])

data[:2]

array([1, 2])

In [29]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [2, 10, 11, 12]])

print(a[a < 5])

[1 2 3 4 2]


In [30]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8 10 11 12]
