In [2]:
import numpy as np

##The Basics


In [3]:
#initialize the array

a = np.array([1,2,3])
print(a)

[1 2 3]


In [8]:
# multi demiensional array
b = np.array([[9,0,3],[3,24,43]])

In [10]:
# get the dimension of the array
#a.ndim
b.ndim

2

In [12]:
# get the shape of the array
#a.shape
b.shape

(2, 3)

In [14]:
#get type
#a.dtype
b.dtype

dtype('int32')

Accessing/Changing specific elements, rows, columns

In [15]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [18]:
# get a specific element [r,c]
a[0,-2]

6

In [19]:
#get a specific row
a[0,:] # all the elements in the first row

array([1, 2, 3, 4, 5, 6, 7])

In [22]:
#get a specific column
a[:,2] # all the elements in the second column

array([ 3, 10])

In [24]:
#more example
a[0,1:6:1] # startindex:endindex:stepsize

array([2, 3, 4, 5, 6])

In [25]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [27]:
#change the value of the array
a[1,3] = 55

In [28]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 55, 12, 13, 14]])

In [29]:
a[:,1] = 7

In [30]:
a

array([[ 1,  7,  3,  4,  5,  6,  7],
       [ 8,  7, 10, 55, 12, 13, 14]])

In [31]:
b = np.array([[1,2],[3,4],[5,6]])
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
b[2,1]

6

Initializing Different Types of Arrays

In [36]:
#All 0s matrix

np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
#All 1s matrix
np.ones(4)

array([1., 1., 1., 1.])

In [39]:
#Any other number
np.full((2,2),4)

array([[4, 4],
       [4, 4]])

In [40]:
#Random decimal numbers

np.random.rand(4,2)

array([[0.67109436, 0.57344127],
       [0.47465031, 0.94925973],
       [0.14013093, 0.99604793],
       [0.32375036, 0.96701796]])

In [47]:
#random integer values
np.random.randint(7,10, size=(3,3))

array([[8, 9, 9],
       [8, 9, 7],
       [7, 9, 7]])

In [51]:
#identity matrix
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [64]:
a = np.ones((5,5))
a[1,1:-1] = 0
a[2,1:-1] = 0
a[3,1:-1] = 0
a[2,2] = 9
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Mathematics

In [66]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [67]:
a + 2

array([3, 4, 5, 6])

In [68]:
a - 2

array([-1,  0,  1,  2])

In [69]:
a * 2

array([2, 4, 6, 8])

In [70]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [71]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

Linear Algebra 

Statistics

In [74]:
stats = np.array([[1,2,3],[4,5,6]])

np.min(stats, axis= 1)

array([1, 4])

In [73]:
np.max(stats)

6

In [75]:
np.sum(stats)

21

Reorganizing Arrays


In [78]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
after

[[1 2 3 4]
 [5 6 7 8]]


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])