1

In [3]:
fruits  = ['apple','banana','orange','grape']

fruits.append('kiwi')
#print(fruits)

fruits.remove('banana')
#print(fruits)

['apple', 'banana', 'orange', 'grape', 'kiwi']
['apple', 'orange', 'grape', 'kiwi']


2

In [1]:
numbers = [1,2,3,4,5,6,7,8,9,10]

first_three = numbers[:3]
#print(first_three)

last_three = numbers[-3:]
#print(last_three)

other_element_from_second = numbers[1:]
#print(other_element_from_second)

3

In [9]:
a = [1,2,4,5,6,7,8,9,10] 




[1, 2, 4, 5, 6, 7, 8, 9, 10, 1, 2, 4, 5, 6, 7, 8, 9, 10]

4

In [12]:
coordinates = ('424324.235235','3235325.3245')

print(f"latitude = {coordinates[0]}")
print(f'longitude = {coordinates[1]}')

latitude = 424324.235235
longitude = 3235325.3245


5

tuples are immutable because it element can not be change. for example declaring a tuple of first 5 integers, if you try to change any of the element it will cause an error

In [3]:
import numpy as np



In [ ]:
import numpy as np



1

In [4]:
arr = np.arange(10)
#arr

2

In [5]:
np.random.rand(3,3)

array([[0.75753744, 0.53979018, 0.95746985],
       [0.35943974, 0.19040069, 0.07862676],
       [0.787912  , 0.44683179, 0.42353021]])

3

In [22]:
arr = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

4

In [23]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

sum = arr1 + arr2
sum

array([ 6,  8, 10, 12])

5

In [27]:
arr = np.array(np.arange(1,10)).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

6

In [56]:
arr = np.array(np.random.randint(1,11,(5,5)))
arr

array([[ 8,  7,  3,  8,  9],
       [10,  6,  7,  8,  1],
       [ 3, 10,  2,  4,  6],
       [ 9,  8,  8,  3,  3],
       [ 7,  8,  8,  8,  8]])